dictionaries = []
words = [
    "allauth",
    "atcb",
    "blockquote",
    "csrfmiddlewaretoken",
    "dataid",
    "dockerfile",
    "dokku",
    "elif",
    "endcomment",
    "endfor",
    "errorlist",
    "eventcalendar",
    "favicons",
    "formset",
    "imagekit",
    "innerhtml",
    "lanczos",
    "lookups",
    "modeladmin",
    "onboarded",
    "posthog",
    "queryset",
    "signup",
    "staticfiles",
    "stylesheet",
    "taggit",
    "tailwindcss",
    "tblue",
    "tcreme",
    "tiedye",
    "totemcircles",
    "tpink",
    "tprose",
    "truetype",
    "truncatewords",
    "tshadow",
    "waitlist",
    "webflow",
    "wght",
    "woff",
    "fieldsets",
    "fcm"
]
flag_words = []
ignore_paths = []
