dictionaries = ["en"]
words = [
    "atcb",
    "blockquote",
    "csrfmiddlewaretoken",
    "dataid",
    "dockerfile",
    "dokku",
    "elif",
    "endcomment",
    "endfor",
    "errorlist",
    "eventcalendar",
    "favicons",
    "imagekit",
    "innerhtml",
    "LANCZOS",
    "onboarded",
    "Posthog",
    "signup",
    "stylesheet",
    "taggit",
    "tailwindcss",
    "tblue",
    "tcreme",
    "TIEDYE",
    "totemcircles",
    "tpink",
    "tprose",
    "truetype",
    "truncatewords",
    "tshadow",
    "waitlist",
    "wght",
    "woff",
]
flag_words = []
ignore_paths = []
