version: "3"

volumes:
  totem_local_postgres_data: {}
  totem_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: totem_local_django
    container_name: totem_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: totem_production_postgres
    container_name: totem_local_postgres
    volumes:
      - totem_local_postgres_data:/var/lib/postgresql/data
      - totem_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  # assets:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/assets/Dockerfile
  #   image: totem_local_assets
  #   container_name: totem_local_assets
